### GET all tasks
GET http://localhost:8080/api/tasks/

### POST a task
POST http://localhost:8080/api/tasks/
Content-Type: application/json

{
    "description": "Task 1"
}

### GET a task
GET http://localhost:8080/api/tasks/1


### PUT a task
PUT http://localhost:8080/api/tasks/1
Content-Type: application/json

{
    "id": 5,
    "description": "Task 1",
    "is_done": true
}

### DELETE a task
DELETE http://localhost:8080/api/tasks/3